/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface SOSAlert {
  'id' : bigint,
  'latitude' : number,
  'name' : string,
  'longitude' : number,
  'message' : string,
  'timestamp' : bigint,
}
export interface SafeZone {
  'id' : bigint,
  'latitude' : number,
  'name' : string,
  'district' : string,
  'state' : string,
  'longitude' : number,
  'zoneType' : string,
}
export interface _SERVICE {
  'filterSafeZonesByState' : ActorMethod<[string], Array<SafeZone>>,
  'filterSafeZonesByType' : ActorMethod<[string], Array<SafeZone>>,
  'getLatestAlerts' : ActorMethod<[], Array<SOSAlert>>,
  'getSafeZones' : ActorMethod<[], Array<SafeZone>>,
  'submitSos' : ActorMethod<[string, string, number, number], SOSAlert>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];