/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SafeZone = IDL.Record({
  'id' : IDL.Nat,
  'latitude' : IDL.Float64,
  'name' : IDL.Text,
  'district' : IDL.Text,
  'state' : IDL.Text,
  'longitude' : IDL.Float64,
  'zoneType' : IDL.Text,
});
export const SOSAlert = IDL.Record({
  'id' : IDL.Nat,
  'latitude' : IDL.Float64,
  'name' : IDL.Text,
  'longitude' : IDL.Float64,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'filterSafeZonesByState' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SafeZone)],
      ['query'],
    ),
  'filterSafeZonesByType' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SafeZone)],
      ['query'],
    ),
  'getLatestAlerts' : IDL.Func([], [IDL.Vec(SOSAlert)], ['query']),
  'getSafeZones' : IDL.Func([], [IDL.Vec(SafeZone)], ['query']),
  'submitSos' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
      [SOSAlert],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SafeZone = IDL.Record({
    'id' : IDL.Nat,
    'latitude' : IDL.Float64,
    'name' : IDL.Text,
    'district' : IDL.Text,
    'state' : IDL.Text,
    'longitude' : IDL.Float64,
    'zoneType' : IDL.Text,
  });
  const SOSAlert = IDL.Record({
    'id' : IDL.Nat,
    'latitude' : IDL.Float64,
    'name' : IDL.Text,
    'longitude' : IDL.Float64,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    'filterSafeZonesByState' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SafeZone)],
        ['query'],
      ),
    'filterSafeZonesByType' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SafeZone)],
        ['query'],
      ),
    'getLatestAlerts' : IDL.Func([], [IDL.Vec(SOSAlert)], ['query']),
    'getSafeZones' : IDL.Func([], [IDL.Vec(SafeZone)], ['query']),
    'submitSos' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
        [SOSAlert],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };